version: '3.7'

services:
  db:
    container_name: Sportify-db
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432
    volumes:
      - usefulpgdata:/var/lib/postgresql/data

  back:
    container_name: Sportify-back
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    volumes:
      - ./:/app
    ports:
      - 8000:80
    restart: always
    depends_on:
      - db
    command: ./start-reload.sh

volumes:
  usefulpgdata:
